### ISSUE TITLE
Consider switching to the VS MEF default catalog

### ISSUE THREAD

**Issue by AArnott** [clariuslabs/clide#28]
Clide current [creates its own MEF catalog and container](https://github.com/clariuslabs/clide/blob/7f047516a17979d1f9d44ff60647c25abe78ccd7/Src/Clide/DevEnvFactory.cs#L117). This makes initialization of a Clide package slower than it otherwise could be.

If instead, Clide components registered themselves in their source.extension.vsixmanifest file as MEF assemblies, VS could cache the catalog and composition and achieve faster startup times for their users.

**Comment by NikGovorov** [comment]
+1, it takes 2-3 seconds to initialise Clide in my extension.

**Comment by kzu** [comment]
If Clide exported its contracts to VS, two extensions using Clide would
cause each other to break because there would be multiples exports of the
same contact. One way around that is to have a "blessed" extension that
does that, and anyone using Clide would take a dependency on it. But now
you get into a very likely situation where two extensions depend on
different versions of that vsix, and loading failures ensure. We've gone
down that route in the past with NuPattern and it was a nightmare.

Also, in some advanced scenarios, you might want/need multiple scopes for
your components (I.e. in Xamarin we have a global set of components, but
also Android and iOS specific ones), and that wouldn't be easy to expose
via a library like Clide since the underlying primitives in VSMEF to
control container creation lives in Microsoft.ExtensibilityHosting which
isn't redirected via devenv.exe.config bindings, making it impossible to
consume unless you have one version of the library for each VS version.

If the IoC container of choice was configurable, we could just expose an
initialization entry point, like CommonComposition already supports, maybe.

I agree though that the reflection-based way of registering components is
an issue. Maybe we should do away altogether with declarative registration
and just explicitly register what we need, MEF2 style (or Autofac or
what-not)

**Comment by AArnott** [comment]
Very good points, @kzu. Given Clide has built-in exports and everyone would ship them individually that would collide in a bad way.

On your point of multiple scopes, VS MEF (starting in VS2015) actually support that. VS MEF supports a combination of .NET MEF and MEF2 attributes, and when you use MEF2 attributes to describes scopes (i.e. named sharing boundaries) VS MEF honors that. We use that already to create scopes for individual projects and configurations. This doesn't require ExtensibilityHosting interactions. We should document how this works.

But ya, unless Clide gets rid of all built-in MEF exports (such that all exports come from user-written code), I don't see it working for you after all.

**Comment by kzu** [comment]
Yup, one alternative I'm toying with is making the nuget package actually just contain a .targets file that adds all the source files in Clide as <Compile />. This would allow it to use VSMEF since all types will belong to the consumer's assembly, rather than Clide's :). 

It would also make it for very easy in-place patching if someone happens to find a bug, before it gets fixed and pushed to nuget. Debugging would also be way better....

**Comment by AArnott** [comment]
@kzu, *No*, including all Clide source files in the extension's assembly would *not* make it compatible with MEF. MEF's contracts are based on contract names and type names *un* qualified by assembly name. So as long as Clide's source files define types with the same namespace as another extension's copy of Clide source code, they'll collide just as much as if Clide shipped as a DLL with each of these extensions.

**Comment by kzu** [comment]
But don't all MEF exports get a "required type identity" metadata too that can be used to filter them?

**Comment by AArnott** [comment]
Yes. But the required type identity is `Type.FullName`, not `Type.AssemblyQualifiedName`. So the assembly that defines the type doesn't matter. If two assemblies define types with the same full names (namespace+name), in MEF they will be seen as equivalent, and you'll get `InvalidCastException` or rejected composition errors everywhere.

**Comment by AArnott** [comment]
I'm asking myself why this was the design in the original MEF. And to tell the truth I don't know. But without it, I suspect embedded types (as in, NoPIA, where a project references an interop DLL that isn't required at runtime) wouldn't work in MEF correctly, since although [the CLR sees these types across assemblies as equivalent](https://msdn.microsoft.com/en-us/library/system.type.isequivalentto(v=vs.110).aspx), and have the same `Type.FullName`, they have different `Type.AssemblyQualifiedName` values.

**Comment by kzu** [comment]
Yeah, good point. Maybe all contracts could come explicitly annotated by
concatenating two constants, one of which would be generated from the
including project's assembly name or something, a sort of prefix.

The annoying thing is that then all imports would need to explicitly
specify the contract names to those same constants :(

It sucks in almost all alternatives I can think of :(

**Comment by AArnott** [comment]
Perhaps we can change VS MEF's behavior to use `AssemblyQualifiedName`, except for interop types.

**Comment by kzu** [comment]
If only that could ship for vs2012+ too :(

**Comment by AArnott** [comment]
ya... sadly no.

**Comment by AArnott** [comment]
Closing since MEF's design and Clide's use of MEF exports that are distributed with each extension seems to be incompatible.
